### ISSUE TITLE
Unable to select category

### ISSUE THREAD

**Issue by mcarlosro** [cyxou/firefly-iii-telegram-bot#15]
Hi, 

thanks for this useful bot. My issue is regarding to having a lot categories (2 pages in the ui) and the categories only display the first page.

Can we add something for paging or filter based on some characters?

Thanks,

**Comment by cyxou** [comment]
Hi @mcarlosro! Or I wasn’t aware of that since I am using not that much categories and they all displayed in a single page. How many do you have? I would like to test your flow…

**Comment by cyxou** [comment]
Regarding displaying of categories in bot. Would it be useful if we add sort of pagination like we have when you list transactions by date? Or should we display a huge list of categories all at once?

**Comment by cyxou** [comment]
Implemented in #23
