### ISSUE TITLE
Feature Request: Increase or customize list of categories

### ISSUE THREAD

**Issue by MrCaringi** [cyxou/firefly-iii-telegram-bot#21]
## It is necessary to increase the quantity of categories listed by the bot,

I suggest two options
- define a new ENVIRONMENT VARIABLE (in docker-compose.yml file) in order to indicate the quantity of categories to be showed
- or maybe paginate the results, using buttons to advance/back the pages

thanks in advance!

**Comment by MrCaringi** [comment]
Just for the records,

some findings:

Official API documentation regarding the categories endpoint:
https://api-docs.firefly-iii.org/#/categories/listCategory

It seems like there is no way to increase the number of items to be returned by the endpoint, is limited to 50,
but it support pagination

I propose two solutions:

## APROACH 1:

ask for the firts page,
and repeat the request for the URL indicated in the element `links.next` until there is no more `links.next` in the API response

![image](https://github.com/cyxou/firefly-iii-telegram-bot/assets/47096567/5351a6a3-7676-42d8-a2c9-b139021ef325)
![image](https://github.com/cyxou/firefly-iii-telegram-bot/assets/47096567/99b2ffb2-0fc6-46a3-9e67-297f50aeed53)

## APROCAH 2

to get the total page number in the first request (without a page value in the query parameter)
meta.pagination.total_pages

this way you can know how many request have to be made

![image](https://github.com/cyxou/firefly-iii-telegram-bot/assets/47096567/e436b095-4dd0-42da-ba21-f06db494664d)

Regards!

**Comment by cyxou** [comment]
implemented in #23
