### ISSUE TITLE
description of a transaction

### ISSUE THREAD

**Issue by gianlucaromito** [cyxou/firefly-iii-telegram-bot#4]
Hello and thanks for this great bot!
if I enter a value the bot asks me the category. I add one, then he ask me to edit or delete. I choose edit and then description. He asks me type in new description. I enter it but the transactions remains with an N/A description.

Thanks for checking.

I use the docker version...

G

**Comment by cyxou** [comment]
Hi @gianlucaromito 

Thanks for reaching out. Unfortunately I could not reproduce the bug you've described. I tried transactions of type Expense and Transfer and description was set correctly in both cases when making edits. Could you please check the same again making sure that you are using the latest docker image.
